# Generated by Django 4.0.7 on 2022-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='guest',
            name='password',
            field=models.CharField(default='emptypassword123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
